apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - secret.yaml

configMapGenerator:
  - name: webui-nginx-config
    files:
      - nginx.conf
    options:
      disableNameSuffixHash: true

images:
  - name: quay.io/rh-sdv-cloud/aib-webui
    newTag: latest
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: ado-webui
      app.kubernetes.io/part-of: automotive-dev-operator
