# permissions for end users to view automotivedevs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: automotive-dev-operator
    app.kubernetes.io/managed-by: kustomize
  name: automotivedev-viewer-role
rules:
- apiGroups:
  - automotive.sdv.cloud.redhat.com
  resources:
  - automotivedevs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - automotive.sdv.cloud.redhat.com
  resources:
  - automotivedevs/status
  verbs:
  - get
