apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "automotive.sdv.cloud.redhat.com/v1",
          "kind": "AutomotiveDevConfig",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "automotive-dev-operator",
              "environment": "development"
            },
            "name": "automotive-dev",
            "namespace": "automotive-dev-operator-system"
          },
          "spec": {
            "buildConfig": {
              "pvcSize": "8Gi"
            }
          },
          "status": {
            "phase": "Ready",
            "message": "AutomotiveDevConfig environment is ready",
            "lastUpdated": "2024-01-15T10:30:00Z"
          }
        },
        {
          "apiVersion": "automotive.sdv.cloud.redhat.com/v1",
          "kind": "ImageBuild",
          "metadata": {
            "annotations": {
              "description": "Example ImageBuild CR. The architecture can be set to any supported value like \"aarch64\", \"x86_64\", etc. See your build platform's documentation for supported values.\n"
            },
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "automotive-dev-operator"
            },
            "name": "imagebuild-sample"
          },
          "spec": {
            "architecture": "amd64",
            "automotiveImageBuilder": "quay.io/centos-sig-automotive/automotive-image-builder:1.0.0",
            "distro": "cs9",
            "exportFormat": "qcow2",
            "manifestConfigMap": "mpp",
            "mode": "image",
            "serveArtifact": false,
            "serveExpiryHours": 24,
            "target": "qemu"
          },
          "status": {
            "phase": "Completed",
            "message": "Image build completed successfully",
            "taskRunName": "imagebuild-sample-run-abc123",
            "pvcName": "imagebuild-sample-pvc",
            "artifactPath": "/workspace/output/image.qcow2",
            "artifactFileName": "image.qcow2",
            "startTime": "2024-01-15T10:00:00Z",
            "completionTime": "2024-01-15T10:25:00Z"
          }
        },
        {
          "apiVersion": "automotive.sdv.cloud.redhat.com/v1",
          "kind": "Image",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "automotive-dev-operator"
            },
            "name": "image-sample"
          },
          "spec": {
            "architecture": "amd64",
            "distro": "cs9",
            "exportFormat": "qcow2",
            "target": "qemu",
            "location": {
              "type": "registry",
              "registry": {
                "url": "quay.io/example/my-image:latest"
              }
            }
          },
          "status": {
            "phase": "Available",
            "message": "Image is available and verified",
            "lastVerified": "2024-01-15T10:30:00Z",
            "lastAccessed": "2024-01-15T11:00:00Z",
            "accessCount": 5
          }
        }
      ]
    capabilities: Basic Install
  name: automotive-dev-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Image is the Schema for the images API
      displayName: Image
      kind: Image
      name: images.automotive.sdv.cloud.redhat.com
      resources:
      - kind: ConfigMap
        name: ""
        version: v1
      specDescriptors:
      - description: Architecture specifies the target architecture
        displayName: Architecture
        path: architecture
      - description: Distro specifies the distribution
        displayName: Distribution
        path: distro
      - description: ExportFormat specifies the output format
        displayName: Export Format
        path: exportFormat
      - description: Target specifies the build target
        displayName: Target
        path: target
      - description: Location defines where the image is stored
        displayName: Location
        path: location
      - description: Type specifies the storage type
        displayName: Location Type
        path: location.type
      statusDescriptors:
      - description: Phase represents the current phase of the image
        displayName: Phase
        path: phase
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.phase
      version: v1
    - description: AutomotiveDevConfig is the Schema for the automotivedevconfigs
        API
      displayName: Automotive Dev Config
      kind: AutomotiveDevConfig
      name: automotivedevconfigs.automotive.sdv.cloud.redhat.com
      version: v1
    - description: ImageBuild is the Schema for the imagebuilds API
      displayName: Image Build
      kind: ImageBuild
      name: imagebuilds.automotive.sdv.cloud.redhat.com
      version: v1
  description: Operator for Automotive Development platform - includes pipelines for
    building AutoSD images
  displayName: Automotive Development Platform
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - automotive
  links:
  - name: Automotive Dev Operator
    url: https://automotive-dev-operator.domain
  maturity: alpha
  minKubeVersion: 1.26.0
  provider:
    name: Red Hat
  version: 0.0.0
