apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: automotive-dev-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AutomotiveDev is the Schema for the automotivedevs API
      displayName: Automotive Dev
      kind: AutomotiveDev
      name: automotivedevs.automotive.sdv.cloud.redhat.com
      version: v1
    - description: ImageBuild is the Schema for the imagebuilds API
      displayName: Image Build
      kind: ImageBuild
      name: imagebuilds.automotive.sdv.cloud.redhat.com
      version: v1
  description: Operator for Automotive Development platform - includes pipelines for
    building AutoSD images
  displayName: Automotive Development Platform
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - automotive
  links:
  - name: Automotive Dev Operator
    url: https://automotive-dev-operator.domain
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
